version: 2
updates:
  # Enable version updates for git submodules
  - package-ecosystem: "gitsubmodule"
    # Look for submodules in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "daily"

